// 护航师数据 - 电竞护航平台
const products = [
    {
        id: 1,
        name: '绝密体验单',
        game: 'lol',
        gameName: '英雄联盟',
        gameIcon: '🛡️',
        serviceType: 'rank',
        serviceTypeName: '上分护航',
        level: '王者',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=player1',
        rating: 4.9,
        sales: 240520,
        price: 64,
        originalPrice: 188.88,
        discount: 65,
        tags: ['高胜率', '语音陪玩', '包上王者'],
        description: '打绝密局 保底最低600万~1000万最高保底无上限！绝无黑单，放心下单！',
        skills: ['中单', 'AP英雄', '战术指挥'],
        winRate: 75,
        averageTime: 3,
        online: true,
        image: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 100%)',
        guarantee: '保底600W-1000W'
    },
    {
        id: 2,
        name: '绝密保底1288w',
        game: 'lol',
        gameName: '英雄联盟',
        gameIcon: '🛡️',
        serviceType: 'rank',
        serviceTypeName: '上分护航',
        level: '最强王者',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=player2',
        rating: 4.8,
        sales: 188000,
        price: 69,
        originalPrice: 188.00,
        discount: 63,
        tags: ['高保底', '极速上分', '技术流'],
        description: '绝密保底1288w或者单局600w 完成其中之一才能结单！不满意全额退款！',
        skills: ['打野', '刺客', '节奏控制'],
        winRate: 78,
        averageTime: 2.5,
        online: true,
        image: 'linear-gradient(135deg, #1a1a2e 0%, #0f3460 100%)',
        guarantee: '保底1288W'
    },
    {
        id: 3,
        name: '新人尝鲜单',
        game: 'honor',
        gameName: '王者荣耀',
        gameIcon: '👑',
        serviceType: 'rank',
        serviceTypeName: '上分护航',
        level: '荣耀王者',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=player3',
        rating: 4.7,
        sales: 156700,
        price: 39,
        originalPrice: 99.00,
        discount: 60,
        tags: ['新人专享', '性价比', '快速上分'],
        description: '王者荣耀百星王者，新人专属优惠！擅长打野和射手，带你轻松上分！',
        skills: ['打野', '射手', '团队配合'],
        winRate: 72,
        averageTime: 2,
        online: true,
        image: 'linear-gradient(135deg, #1a1a2e 0%, #533483 100%)',
        guarantee: '保底300W'
    },
    {
        id: 4,
        name: '超级亏本单',
        game: 'csgo',
        gameName: 'CS:GO',
        gameIcon: '🔫',
        serviceType: 'private',
        serviceTypeName: '私人陪练',
        level: '传奇',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=player4',
        rating: 5.0,
        sales: 85600,
        price: 89,
        originalPrice: 299.00,
        discount: 70,
        tags: ['职业级', '枪法教学', '亏本冲量'],
        description: '前职业选手，亏本冲销量！提供AWP和步枪教学，快速提升竞技水平！',
        skills: ['AWP', '步枪', '战术指挥'],
        winRate: 82,
        averageTime: 4,
        online: true,
        image: 'linear-gradient(135deg, #1a1a2e 0%, #e94560 100%)',
        guarantee: '保底500W'
    },
    {
        id: 5,
        name: '保底300单',
        game: 'pubg',
        gameName: '绝地求生',
        gameIcon: '🎯',
        serviceType: 'rank',
        serviceTypeName: '上分护航',
        level: '超级王牌',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=player5',
        rating: 4.6,
        sales: 120000,
        price: 49,
        originalPrice: 128.00,
        discount: 61,
        tags: ['无敌身法', '老六流', '四排开黑'],
        description: 'PUBG超级王牌段位，保底300W！擅长身法走位和战术配合，四排开黑包鸡！',
        skills: ['身法', '战术', '团队配合'],
        winRate: 70,
        averageTime: 3.5,
        online: false,
        image: 'linear-gradient(135deg, #1a1a2e 0%, #f5a623 100%)',
        guarantee: '保底300W'
    },
    {
        id: 6,
        name: '保底150单',
        game: 'peace',
        gameName: '和平精英',
        gameIcon: '🎖️',
        serviceType: 'entertainment',
        serviceTypeName: '娱乐陪玩',
        level: '王牌',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=player6',
        rating: 4.9,
        sales: 200000,
        price: 29,
        originalPrice: 79.00,
        discount: 63,
        tags: ['声音好听', '搞笑', '陪玩'],
        description: '和平精英王牌段位，声音超好听！保底150W！适合想轻松游戏的玩家！',
        skills: ['娱乐', '解说', '组队'],
        winRate: 68,
        averageTime: 3,
        online: true,
        image: 'linear-gradient(135deg, #1a1a2e 0%, #52c41a 100%)',
        guarantee: '保底150W'
    },
    {
        id: 7,
        name: '保底500单',
        game: 'valorant',
        gameName: '无畏契约',
        gameIcon: '⚡',
        serviceType: 'rank',
        serviceTypeName: '上分护航',
        level: '超凡',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=player7',
        rating: 4.8,
        sales: 98700,
        price: 59,
        originalPrice: 159.00,
        discount: 62,
        tags: ['超凡大师', '突破手', '教学'],
        description: '无畏契约超凡大师段位，保底500W！擅长突破手角色，帮你快速上分！',
        skills: ['突破', '急停', '道具使用'],
        winRate: 73,
        averageTime: 3,
        online: true,
        image: 'linear-gradient(135deg, #1a1a2e 0%, #ff4655 100%)',
        guarantee: '保底500W'
    },
    {
        id: 8,
        name: '保底1个亿',
        game: 'dota2',
        gameName: 'DOTA2',
        gameIcon: '⚔️',
        serviceType: 'tutorial',
        serviceTypeName: '教学指导',
        level: '王者',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=player8',
        rating: 4.9,
        sales: 65400,
        price: 99,
        originalPrice: 299.00,
        discount: 67,
        tags: ['多年经验', '战术教学', '意识培养'],
        description: 'DOTA2十年老玩家，保底1个亿！擅长核心位置教学，全面提升游戏意识！',
        skills: ['核心', '意识', '团战'],
        winRate: 72,
        averageTime: 4,
        online: true,
        image: 'linear-gradient(135deg, #1a1a2e 0%, #c0392b 100%)',
        guarantee: '保底1亿'
    },
    {
        id: 9,
        name: '怪兽卷死单',
        game: 'lol',
        gameName: '英雄联盟',
        gameIcon: '🛡️',
        serviceType: 'rank',
        serviceTypeName: '上分护航',
        level: '最强王者',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=player9',
        rating: 4.9,
        sales: 300000,
        price: 79,
        originalPrice: 199.00,
        discount: 60,
        tags: ['热销爆款', '卷死同行', '超高胜率'],
        description: '热销爆款！卷死同行价格！超高胜率保证上分，不满意全额退款！',
        skills: ['全位置', '指挥', '带飞'],
        winRate: 80,
        averageTime: 2.5,
        online: true,
        image: 'linear-gradient(135deg, #1a1a2e 0%, #ffd700 100%)',
        guarantee: '保底800W'
    },
    {
        id: 10,
        name: '我来当富翁',
        game: 'honor',
        gameName: '王者荣耀',
        gameIcon: '👑',
        serviceType: 'private',
        serviceTypeName: '私人陪练',
        level: '荣耀王者',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=player10',
        rating: 4.7,
        sales: 150000,
        price: 45,
        originalPrice: 128.00,
        discount: 64,
        tags: ['娱乐陪玩', '声音好听', '带飞'],
        description: '王者荣耀娱乐陪玩，声音超好听！带你上分的同时享受欢乐时光！',
        skills: ['娱乐', '带飞', '聊天'],
        winRate: 65,
        averageTime: 3,
        online: true,
        image: 'linear-gradient(135deg, #1a1a2e 0%, #f093fb 100%)',
        guarantee: '保底200W'
    },
    {
        id: 11,
        name: 'AZ3专属单',
        game: 'csgo',
        gameName: 'CS:GO',
        gameIcon: '🔫',
        serviceType: 'private',
        serviceTypeName: '私人陪练',
        level: '传奇',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=player11',
        rating: 5.0,
        sales: 45600,
        price: 129,
        originalPrice: 399.00,
        discount: 67,
        tags: ['专属定制', '职业教练', '系统教学'],
        description: 'AZ3专属定制服务！前职业选手一对一教学，快速提升竞技水平！',
        skills: ['教学', '战术', '进阶'],
        winRate: 85,
        averageTime: 4,
        online: true,
        image: 'linear-gradient(135deg, #1a1a2e 0%, #4facfe 100%)',
        guarantee: '保底1000W'
    },
    {
        id: 12,
        name: '战地空投保底',
        game: 'valorant',
        gameName: '无畏契约',
        gameIcon: '⚡',
        serviceType: 'rank',
        serviceTypeName: '上分护航',
        level: '超凡',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=player12',
        rating: 4.8,
        sales: 78000,
        price: 69,
        originalPrice: 188.00,
        discount: 63,
        tags: ['基础保底', '快速上分', '性价比高'],
        description: '无畏契约基础保底500W！性价比超高，适合新手快速上分！',
        skills: ['突破', '急停', '配合'],
        winRate: 70,
        averageTime: 3,
        online: true,
        image: 'linear-gradient(135deg, #1a1a2e 0%, #96ceb4 100%)',
        guarantee: '保底500W'
    }
];

// 游戏分类配置
const gameCategories = {
    all: { name: '全部', icon: '🎮', color: 'linear-gradient(135deg, #ffd700, #ffa500)' },
    lol: { name: '英雄联盟', icon: '🛡️', color: 'linear-gradient(135deg, #00b0f0, #006ad4)' },
    honor: { name: '王者荣耀', icon: '👑', color: 'linear-gradient(135deg, #ffd700, #ff8c00)' },
    csgo: { name: 'CS:GO', icon: '🔫', color: 'linear-gradient(135deg, #ff4500, #ff6347)' },
    pubg: { name: '绝地求生', icon: '🎯', color: 'linear-gradient(135deg, #f5a623, #d48806)' },
    peace: { name: '和平精英', icon: '🎖️', color: 'linear-gradient(135deg, #52c41a, #389e0d)' },
    valorant: { name: '无畏契约', icon: '⚡', color: 'linear-gradient(135deg, #ff4655, #c4303b)' },
    dota2: { name: 'DOTA2', icon: '⚔️', color: 'linear-gradient(135deg, #c0392b, #922b21)' }
};

// 服务类型配置
const serviceTypes = {
    rank: { name: '上分护航', icon: '📈', description: '快速提升段位' },
    private: { name: '私人陪练', icon: '👤', description: '一对一专属服务' },
    entertainment: { name: '娱乐陪玩', icon: '🎭', description: '轻松娱乐体验' },
    tutorial: { name: '教学指导', icon: '📚', description: '专业技能提升' }
};