// 护航师数据
const products = [
    {
        id: 1,
        name: '星空大师',
        game: 'lol',
        gameName: '英雄联盟',
        gameIcon: '🛡️',
        serviceType: 'rank',
        serviceTypeName: '上分护航',
        level: '王者',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=player1',
        rating: 4.9,
        sales: 1258,
        price: 299,
        originalPrice: 399,
        discount: 25,
        tags: ['高胜率', '语音陪玩', '包上王者'],
        description: '五年电竞选手出身，精通中单AP英雄，擅长卡牌、辛德拉、阿狸等。胜率高达75%，保证包上王者段位！',
        skills: ['中单', 'AP英雄', '战术指挥'],
        winRate: 75,
        averageTime: 3,
        online: true,
        image: 'linear-gradient(135deg, #00b0f0 0%, #006ad4 100%)'
    },
    {
        id: 2,
        name: '月光刺客',
        game: 'honor',
        gameName: '王者荣耀',
        gameIcon: '👑',
        serviceType: 'rank',
        serviceTypeName: '上分护航',
        level: '荣耀王者',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=player2',
        rating: 4.8,
        sales: 2035,
        price: 199,
        originalPrice: 269,
        discount: 26,
        tags: ['百星王者', '极速上分', '技术流'],
        description: '王者荣耀百星王者，擅长打野和刺客英雄，韩信、兰陵王、韩信一手绝活。擅长节奏把控，快速带飞！',
        skills: ['打野', '刺客', '节奏控制'],
        winRate: 78,
        averageTime: 2.5,
        online: true,
        image: 'linear-gradient(135deg, #ffd700 0%, #ff8c00 100%)'
    },
    {
        id: 3,
        name: '雷霆狙神',
        game: 'csgo',
        gameName: 'CS:GO',
        gameIcon: '🔫',
        serviceType: 'private',
        serviceTypeName: '私人陪练',
        level: '传奇',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=player3',
        rating: 5.0,
        sales: 856,
        price: 499,
        originalPrice: 599,
        discount: 17,
        tags: ['职业级', '枪法教学', '战术指导'],
        description: '前职业选手，CS:GO传奇等级，擅长AWP狙击和步枪精通。提供一对一枪法训练和战术指导，快速提升竞技水平！',
        skills: ['AWP', '步枪', '战术指挥'],
        winRate: 82,
        averageTime: 4,
        online: true,
        image: 'linear-gradient(135deg, #ff4500 0%, #ff6347 100%)'
    },
    {
        id: 4,
        name: '吃鸡小王子',
        game: 'pubg',
        gameName: '绝地求生',
        gameIcon: '🎯',
        serviceType: 'rank',
        serviceTypeName: '上分护航',
        level: '超级王牌',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=player4',
        rating: 4.7,
        sales: 1567,
        price: 249,
        originalPrice: 329,
        discount: 24,
        tags: ['无敌身法', '老六流', '四排开黑'],
        description: 'PUBG超级王牌段位，擅长身法走位和战术配合。四排开黑包鸡，保证每局都有精彩表现！',
        skills: ['身法', '战术', '团队配合'],
        winRate: 70,
        averageTime: 3.5,
        online: false,
        image: 'linear-gradient(135deg, #f5a623 0%, #d48806 100%)'
    },
    {
        id: 5,
        name: '和平精英大神',
        game: 'peace',
        gameName: '和平精英',
        gameIcon: '🎖️',
        serviceType: 'entertainment',
        serviceTypeName: '娱乐陪玩',
        level: '王牌',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=player5',
        rating: 4.9,
        sales: 3200,
        price: 159,
        originalPrice: 219,
        discount: 27,
        tags: ['声音好听', '搞笑', '陪玩'],
        description: '和平精英王牌段位，声音超好听！擅长搞笑解说，陪你一起吃鸡。适合想轻松游戏的玩家！',
        skills: ['娱乐', '解说', '组队'],
        winRate: 68,
        averageTime: 3,
        online: true,
        image: 'linear-gradient(135deg, #52c41a 0%, #389e0d 100%)'
    },
    {
        id: 6,
        name: '瓦罗兰之怒',
        game: 'valorant',
        gameName: '无畏契约',
        gameIcon: '⚡',
        serviceType: 'rank',
        serviceTypeName: '上分护航',
        level: '超凡',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=player6',
        rating: 4.8,
        sales: 987,
        price: 269,
        originalPrice: 359,
        discount: 25,
        tags: ['超凡大师', '突破手', '教学'],
        description: '无畏契约超凡大师段位，擅长突破手角色。提供段位提升和技能教学，帮你快速上分！',
        skills: ['突破', '急停', '道具使用'],
        winRate: 73,
        averageTime: 3,
        online: true,
        image: 'linear-gradient(135deg, #ff4655 0%, #c4303b 100%)'
    },
    {
        id: 7,
        name: 'DOTA2老玩家',
        game: 'dota2',
        gameName: 'DOTA2',
        gameIcon: '⚔️',
        serviceType: 'tutorial',
        serviceTypeName: '教学指导',
        level: '王者',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=player7',
        rating: 4.9,
        sales: 654,
        price: 349,
        originalPrice: 449,
        discount: 22,
        tags: ['多年经验', '战术教学', '意识培养'],
        description: 'DOTA2十年老玩家，擅长核心位置教学。从基础到进阶，全面提升你的游戏意识和操作水平！',
        skills: ['核心', '意识', '团战'],
        winRate: 72,
        averageTime: 4,
        online: true,
        image: 'linear-gradient(135deg, #c0392b 0%, #922b21 100%)'
    },
    {
        id: 8,
        name: ' ADC小王子',
        game: 'lol',
        gameName: '英雄联盟',
        gameIcon: '🛡️',
        serviceType: 'private',
        serviceTypeName: '私人陪练',
        level: '宗师',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=player8',
        rating: 4.7,
        sales: 1120,
        price: 279,
        originalPrice: 369,
        discount: 24,
        tags: ['ADC绝活', '走位教学', '团战指挥'],
        description: '英雄联盟ADC绝活哥，擅长金克丝、薇恩、厄斐琉斯。教你完美走位和团战输出最大化！',
        skills: ['ADC', '走位', '输出'],
        winRate: 71,
        averageTime: 3,
        online: false,
        image: 'linear-gradient(135deg, #00b0f0 0%, #006ad4 100%)'
    },
    {
        id: 9,
        name: '王者辅助',
        game: 'honor',
        gameName: '王者荣耀',
        gameIcon: '👑',
        serviceType: 'rank',
        serviceTypeName: '上分护航',
        level: '荣耀王者',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=player9',
        rating: 4.8,
        sales: 1890,
        price: 189,
        originalPrice: 259,
        discount: 27,
        tags: ['辅助绝活', '意识强', '带飞'],
        description: '王者荣耀辅助绝活，张飞、蔡文姬、瑶一手绝活。意识超前，完美保护carry位，带你轻松上分！',
        skills: ['辅助', '保护', '意识'],
        winRate: 74,
        averageTime: 2.5,
        online: true,
        image: 'linear-gradient(135deg, #ffd700 0%, #ff8c00 100%)'
    },
    {
        id: 10,
        name: 'CS2狙击手',
        game: 'csgo',
        gameName: 'CS:GO',
        gameIcon: '🔫',
        serviceType: 'rank',
        serviceTypeName: '上分护航',
        level: '传奇',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=player10',
        rating: 4.9,
        sales: 723,
        price: 399,
        originalPrice: 499,
        discount: 20,
        tags: ['AWP专家', '速刷', '包传奇'],
        description: 'CS2传奇段位，AWP狙击手。速刷模式快速上分，保证效率！适合想快速提升段位的玩家！',
        skills: ['AWP', '速刷', '精准'],
        winRate: 79,
        averageTime: 3.5,
        online: true,
        image: 'linear-gradient(135deg, #ff4500 0%, #ff6347 100%)'
    },
    {
        id: 11,
        name: '和平娱乐王',
        game: 'peace',
        gameName: '和平精英',
        gameIcon: '🎖️',
        serviceType: 'entertainment',
        serviceTypeName: '娱乐陪玩',
        level: '王牌',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=player11',
        rating: 4.6,
        sales: 2450,
        price: 129,
        originalPrice: 189,
        discount: 32,
        tags: ['搞笑', '开黑', '陪聊'],
        description: '和平精英娱乐陪玩，声音超好听！陪你一起开黑吃鸡，轻松愉快的游戏体验！',
        skills: ['娱乐', '开黑', '聊天'],
        winRate: 65,
        averageTime: 3,
        online: true,
        image: 'linear-gradient(135deg, #52c41a 0%, #389e0d 100%)'
    },
    {
        id: 12,
        name: 'VCT教练',
        game: 'valorant',
        gameName: '无畏契约',
        gameIcon: '⚡',
        serviceType: 'tutorial',
        serviceTypeName: '教学指导',
        level: '神话',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=player12',
        rating: 5.0,
        sales: 456,
        price: 459,
        originalPrice: 599,
        discount: 23,
        tags: ['职业教练', '系统教学', '进阶'],
        description: '前VCT职业选手，提供系统化教学。从基础操作到高级战术，全面提升你的竞技水平！',
        skills: ['教学', '战术', '进阶'],
        winRate: 85,
        averageTime: 4,
        online: true,
        image: 'linear-gradient(135deg, #ff4655 0%, #c4303b 100%)'
    }
];

// 游戏分类配置
const gameCategories = {
    all: { name: '全部', icon: '🎮', color: 'linear-gradient(135deg, #667eea, #764ba2)' },
    lol: { name: '英雄联盟', icon: '🛡️', color: 'linear-gradient(135deg, #00b0f0, #006ad4)' },
    honor: { name: '王者荣耀', icon: '👑', color: 'linear-gradient(135deg, #ffd700, #ff8c00)' },
    csgo: { name: 'CS:GO', icon: '🔫', color: 'linear-gradient(135deg, #ff4500, #ff6347)' },
    pubg: { name: '绝地求生', icon: '🎯', color: 'linear-gradient(135deg, #f5a623, #d48806)' },
    peace: { name: '和平精英', icon: '🎖️', color: 'linear-gradient(135deg, #52c41a, #389e0d)' },
    valorant: { name: '无畏契约', icon: '⚡', color: 'linear-gradient(135deg, #ff4655, #c4303b)' },
    dota2: { name: 'DOTA2', icon: '⚔️', color: 'linear-gradient(135deg, #c0392b, #922b21)' }
};

// 服务类型配置
const serviceTypes = {
    rank: { name: '上分护航', icon: '📈', description: '快速提升段位' },
    private: { name: '私人陪练', icon: '👤', description: '一对一专属服务' },
    entertainment: { name: '娱乐陪玩', icon: '🎭', description: '轻松娱乐体验' },
    tutorial: { name: '教学指导', icon: '📚', description: '专业技能提升' }
};